# -*- coding: utf-8 -*-
#patterns
compact = {'blank': ' ',
           'light_horizontal': '-',
           'light_vertical': '|',
           'light_vertical_and_horizontal': '+',
           'light_down_and_horizontal': u'+',
           'light_up_and_horizontal': u'+',
           'light_vertical_and_right': u'+',
           'light_vertical_and_left': u'+',
           'light_down_and_right': u'+',
           'light_down_and_left': u'+',
           'light_up_and_left': u'+',           
           'light_up_and_right': u'+',
           'heavy_horizontal': 'X',
           'heavy_vertical': u'X',
           'heavy_vertical_and_horizontal': '#',
           'player_0': 'A', 
           'player_1': 'B', 
           'player_2': 'C', 
           'player_3': 'D'
          }
box_drawing = {'blank': ' ',
               'light_horizontal': u'─',
               'light_vertical': u'│',
               'light_vertical_and_horizontal': u'┼',
               'light_down_and_horizontal': u'┬',
               'light_up_and_horizontal': u'┴',
               'light_vertical_and_right': u'├',
               'light_vertical_and_left': u'┤',
               'light_down_and_right': u'╭',
               'light_down_and_left': u'╮',
               'light_up_and_left': u'╯',           
               'light_up_and_right': u'╰',
               'heavy_horizontal': u'━',
               'heavy_vertical': u'┃',
               'heavy_vertical_and_horizontal': u'╋',
               'vertical_heavy_and_horizontal_light': u'╂',
               'vertical_light_and_horizontal_heavy': u'┿',
               'player_0': u'█', 
               'player_1': u'▓', 
               'player_2': u'▒', 
               'player_3': u'░'    
              }
classic = {'blank': ' ',
           'light_horizontal': u'─',
           'light_vertical': u'│',
           'light_vertical_and_horizontal': u'┼',
           'light_down_and_horizontal': u'┬',
           'light_up_and_horizontal': u'┴',
           'light_vertical_and_right': u'├',
           'light_vertical_and_left': u'┤',
           'light_down_and_right': u'┌',
           'light_down_and_left': u'┐',
           'light_up_and_left': u'┘',           
           'light_up_and_right': u'└',
           'heavy_horizontal': u'═',
           'heavy_vertical': u'║',
           'heavy_vertical_and_horizontal': u'╬',
           'vertical_heavy_and_horizontal_light': u'╫',
           'vertical_light_and_horizontal_heavy': u'╪',               
           'player_0': u'█', 
           'player_1': u'▓', 
           'player_2': u'▒', 
           'player_3': u'░'    
          }
multicolored = {'blank': ' ',
                'light_horizontal': u'─',
                'light_vertical': u'│',
                'light_vertical_and_horizontal': u'┼',
                'light_down_and_horizontal': u'┬',
                'light_up_and_horizontal': u'┴',
                'light_vertical_and_right': u'├',
                'light_vertical_and_left': u'┤',
                'light_down_and_right': u'┌',
                'light_down_and_left': u'┐',
                'light_up_and_left': u'┘',           
                'light_up_and_right': u'└',
                'heavy_horizontal': u'═',
                'heavy_vertical': u'║',
                'heavy_vertical_and_horizontal': u'╬',
                'vertical_heavy_and_horizontal_light': u'╫',
                'vertical_light_and_horizontal_heavy': u'╪',
                'red': u'\033[31m', #u'\033[101m',
                'green': u'\033[32m', #u'\033[102m'   
                'blue': u'\033[34m', #u'\033[104m'
                'yellow': u'\033[33m', #u'\033[103m'
                'player_0': u'\033[01m' + ' ' + u'\033[0m', 
                'player_1': u'\033[01m' + ' ' + u'\033[0m', 
                'player_2': u'\033[01m' + ' ' + u'\033[0m', 
                'player_3': u'\033[01m' + ' ' + u'\033[0m'    
               }
